### ISSUE TITLE
Figure out a name. 

### ISSUE THREAD

**Issue by LindseyB** [LindseyB/DoATea#27]

**Comment by krainboltgreene** [comment]
What should the name reflect?

**Comment by LindseyB** [comment]
@krainboltgreene not really sure - that's part of the problem - my goal is to create a ridiculous tea game where you just make tea but I dunno how to represent that in a name

**Comment by krainboltgreene** [comment]
teatotalitarian? TeaMon?

**Comment by LindseyB** [comment]
So far I have some ideas: 
- Is it tea?
- Uni-tea
- Cuppa tea (current front runner)

**Comment by krainboltgreene** [comment]
Cuppa Tea wins for me.

On Sat, Jun 20, 2015 at 10:01 PM, Lindsey Bieda notifications@github.com
wrote:

> So far I have some ideas:
> - Is it tea?
> - Uni-tea
> - Cuppa tea (current front runner)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/LindseyB/DoATea/issues/27#issuecomment-113858412.

## 

Kurtis Rainbolt-Greene, Hacker
Software Developer
1631 8th St.
New Orleans, LA
70115

**Comment by LindseyB** [comment]
I like it. Decided!
